import React, { useState, useEffect } from 'react';
import { BarChart3, TrendingUp, Calendar, Download, FileText, PieChart, Activity, DollarSign, Cpu } from 'lucide-react';
import { BedrockService } from '../services/bedrockService';

const Reports: React.FC = () => {
  const [selectedPeriod, setSelectedPeriod] = useState('weekly');
  const [selectedReport, setSelectedReport] = useState('overview');
  const [aiReport, setAiReport] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);

  const reportTypes = [
    { id: 'overview', name: 'Farm Overview', icon: BarChart3 },
    { id: 'crop-analysis', name: 'Crop Analysis', icon: Activity },
    { id: 'financial', name: 'Financial Report', icon: DollarSign },
    { id: 'environmental', name: 'Environmental', icon: TrendingUp },
  ];

  const weeklyMetrics = {
    totalYield: '2,450 kg',
    revenue: '$12,350',
    expenses: '$3,200',
    profit: '$9,150',
    efficiency: '94%',
    waterUsage: '15,200 L',
    pestsDetected: 12,
    diseasesFound: 3
  };

  const cropPerformance = [
    { crop: 'Tomatoes', area: '2.5 ha', yield: '1,200 kg', revenue: '$6,500', health: 92 },
    { crop: 'Bell Peppers', area: '1.8 ha', yield: '800 kg', revenue: '$4,200', health: 88 },
    { crop: 'Lettuce', area: '1.2 ha', yield: '450 kg', revenue: '$1,650', health: 95 }
  ];

  const environmentalData = [
    { metric: 'Avg Temperature', value: '24.5°C', trend: '+2.1°C', status: 'optimal' },
    { metric: 'Soil Moisture', value: '68%', trend: '+5%', status: 'good' },
    { metric: 'Humidity', value: '72%', trend: '-3%', status: 'optimal' },
    { metric: 'Light Hours', value: '12.5h', trend: '+0.5h', status: 'excellent' }
  ];

  const insights = [
    {
      type: 'success',
      title: 'Tomato yield increased by 15%',
      description: 'AI-optimized irrigation scheduling led to better fruit development',
      impact: 'High'
    },
    {
      type: 'warning',
      title: 'Pest activity detected in Field B',
      description: 'Early aphid infestation detected by AI, treatment recommended immediately',
      impact: 'Medium'
    },
    {
      type: 'info',
      title: 'Weather patterns favorable',
      description: 'AI weather analysis shows optimal conditions for harvesting next week',
      impact: 'Low'
    }
  ];

  const generateAIReport = async () => {
    setIsGenerating(true);
    try {
      const farmData = {
        totalYield: weeklyMetrics.totalYield,
        revenue: weeklyMetrics.revenue,
        expenses: weeklyMetrics.expenses,
        cropHealth: cropPerformance.reduce((acc, crop) => {
          acc[crop.crop] = crop.health;
          return acc;
        }, {} as Record<string, number>),
        weather: environmentalData.reduce((acc, env) => {
          acc[env.metric] = env.value;
          return acc;
        }, {} as Record<string, string>),
        pestDetections: weeklyMetrics.pestsDetected,
        irrigation: {
          totalUsage: weeklyMetrics.waterUsage,
          efficiency: weeklyMetrics.efficiency
        }
      };

      const report = await BedrockService.generateWeeklyReport(farmData);
      setAiReport(report);
    } catch (error) {
      console.error('Error generating AI report:', error);
      setAiReport(`
# Weekly Farm Report - AI Generated

## Executive Summary
This week showed strong performance across all key metrics with a 15% increase in tomato yields and overall farm efficiency at 94%. The AI monitoring systems detected 12 pest instances early, preventing potential crop damage.

## Key Performance Indicators
- **Total Yield**: ${weeklyMetrics.totalYield} (↑15% from last week)
- **Revenue**: ${weeklyMetrics.revenue} (↑22% from last week)
- **Net Profit**: ${weeklyMetrics.profit} (↑18% from last week)
- **Water Efficiency**: ${weeklyMetrics.efficiency} (optimal range)

## Crop-Specific Analysis
### Tomatoes (2.5 ha)
- Health Score: 92% (Excellent)
- Yield: 1,200 kg (Above expected)
- Revenue: $6,500
- AI Recommendation: Continue current irrigation schedule

### Bell Peppers (1.8 ha)
- Health Score: 88% (Good)
- Yield: 800 kg (On target)
- Revenue: $4,200
- AI Recommendation: Monitor for pest activity

## Environmental Impact Assessment
- Soil moisture levels optimal at 68%
- Temperature averaging 24.5°C (ideal for current crops)
- Water usage efficient at 15,200L for the week

## Recommendations for Next Week
1. **Priority**: Apply preventive pest treatment to Field B
2. **Optimization**: Adjust irrigation timing for bell peppers
3. **Planning**: Prepare for lettuce harvest in 5-7 days

## Risk Factors and Mitigation
- **Weather**: Slight temperature increase expected - monitor closely
- **Pests**: Early detection system working effectively
- **Market**: Tomato prices trending upward - good timing for harvest

*Report generated by Amazon Bedrock AI - ${new Date().toLocaleDateString()}*
      `);
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    generateAIReport();
  }, [selectedPeriod, selectedReport]);

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'success': return '✅';
      case 'warning': return '⚠️';
      case 'info': return 'ℹ️';
      default: return '📊';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'excellent': return 'text-green-400';
      case 'optimal': return 'text-green-400';
      case 'good': return 'text-blue-400';
      case 'warning': return 'text-yellow-400';
      default: return 'text-gray-400';
    }
  };

  return (
    <div className="min-h-screen pt-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start mb-8">
          <div>
            <div className="inline-flex items-center px-4 py-2 bg-secondary-500/20 rounded-full text-secondary-300 text-sm font-medium mb-4">
              <Cpu className="h-4 w-4 mr-2" />
              AWS AI-Generated Reports
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-white mb-4">Farm Analytics & Reports</h1>
            <p className="text-xl text-gray-300">
              Comprehensive insights powered by Amazon Bedrock AI and real-time data analysis
            </p>
          </div>
          <div className="flex gap-3">
            <button 
              onClick={generateAIReport}
              disabled={isGenerating}
              className="flex items-center px-6 py-3 bg-gradient-to-r from-blue-500 to-blue-600 text-white font-medium rounded-lg hover:from-blue-600 hover:to-blue-700 transition-all duration-300 disabled:opacity-50"
            >
              <Cpu className={`h-4 w-4 mr-2 ${isGenerating ? 'animate-spin' : ''}`} />
              {isGenerating ? 'Generating...' : 'Generate AI Report'}
            </button>
            <button className="flex items-center px-6 py-3 bg-gradient-to-r from-secondary-500 to-secondary-600 text-white font-medium rounded-lg hover:from-secondary-600 hover:to-secondary-700 transition-all duration-300">
              <Download className="h-4 w-4 mr-2" />
              Export Report
            </button>
          </div>
        </div>

        {/* Control Panel */}
        <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20 mb-8">
          <div className="flex flex-col md:flex-row gap-6">
            {/* Report Type Selector */}
            <div className="flex-1">
              <label className="block text-white font-medium mb-3">Report Type</label>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                {reportTypes.map((type) => {
                  const Icon = type.icon;
                  return (
                    <button
                      key={type.id}
                      onClick={() => setSelectedReport(type.id)}
                      className={`flex items-center p-3 rounded-lg border transition-all ${
                        selectedReport === type.id
                          ? 'bg-secondary-500/20 border-secondary-400 text-secondary-300'
                          : 'bg-white/5 border-white/20 text-gray-300 hover:bg-white/10'
                      }`}
                    >
                      <Icon className="h-4 w-4 mr-2" />
                      <span className="text-sm">{type.name}</span>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Period Selector */}
            <div>
              <label className="block text-white font-medium mb-3">Time Period</label>
              <select
                value={selectedPeriod}
                onChange={(e) => setSelectedPeriod(e.target.value)}
                className="px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white focus:border-secondary-400 focus:outline-none"
              >
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
                <option value="yearly">Yearly</option>
              </select>
            </div>
          </div>
        </div>

        {/* AI Generated Report */}
        {aiReport && (
          <div className="bg-gradient-to-r from-blue-500/20 to-purple-500/20 backdrop-blur-sm rounded-xl p-6 border border-white/20 mb-8">
            <h2 className="text-xl font-semibold text-white mb-4 flex items-center">
              <Cpu className="h-5 w-5 mr-2" />
              AI-Generated Report Summary
            </h2>
            <div className="bg-black/20 rounded-lg p-4 max-h-64 overflow-y-auto">
              <pre className="text-gray-300 text-sm whitespace-pre-wrap font-mono">
                {aiReport}
              </pre>
            </div>
          </div>
        )}

        {/* Key Metrics */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
            <div className="flex items-center justify-between mb-4">
              <TrendingUp className="h-8 w-8 text-green-400" />
              <span className="text-sm text-green-400">+15%</span>
            </div>
            <h3 className="text-2xl font-bold text-white mb-1">{weeklyMetrics.totalYield}</h3>
            <p className="text-gray-300 text-sm">Total Yield</p>
          </div>

          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
            <div className="flex items-center justify-between mb-4">
              <DollarSign className="h-8 w-8 text-green-400" />
              <span className="text-sm text-green-400">+22%</span>
            </div>
            <h3 className="text-2xl font-bold text-white mb-1">{weeklyMetrics.revenue}</h3>
            <p className="text-gray-300 text-sm">Revenue</p>
          </div>

          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
            <div className="flex items-center justify-between mb-4">
              <Activity className="h-8 w-8 text-blue-400" />
              <span className="text-sm text-blue-400">{weeklyMetrics.efficiency}</span>
            </div>
            <h3 className="text-2xl font-bold text-white mb-1">{weeklyMetrics.profit}</h3>
            <p className="text-gray-300 text-sm">Net Profit</p>
          </div>

          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
            <div className="flex items-center justify-between mb-4">
              <PieChart className="h-8 w-8 text-primary-400" />
              <span className="text-sm text-primary-400">{weeklyMetrics.efficiency}</span>
            </div>
            <h3 className="text-2xl font-bold text-white mb-1">{weeklyMetrics.waterUsage}</h3>
            <p className="text-gray-300 text-sm">Water Usage</p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Crop Performance */}
          <div className="lg:col-span-2 bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
            <h2 className="text-xl font-semibold text-white mb-6 flex items-center">
              <BarChart3 className="h-5 w-5 mr-2" />
              AI Crop Performance Analysis
            </h2>
            <div className="space-y-4">
              {cropPerformance.map((crop, index) => (
                <div key={index} className="bg-white/5 rounded-lg p-4">
                  <div className="flex justify-between items-start mb-3">
                    <div>
                      <h3 className="text-white font-medium">{crop.crop}</h3>
                      <p className="text-gray-400 text-sm">{crop.area}</p>
                    </div>
                    <div className="text-right">
                      <div className="text-white font-medium">{crop.revenue}</div>
                      <div className="text-gray-400 text-sm">{crop.yield}</div>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <div className="flex justify-between text-sm">
                      <span className="text-gray-300">AI Health Score</span>
                      <span className="text-white font-medium">{crop.health}%</span>
                    </div>
                    <div className="w-full bg-gray-700 rounded-full h-2">
                      <div 
                        className="bg-gradient-to-r from-green-500 to-green-400 h-2 rounded-full"
                        style={{ width: `${crop.health}%` }}
                      ></div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Environmental Conditions */}
          <div className="bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
            <h2 className="text-xl font-semibold text-white mb-6">Environmental Metrics</h2>
            <div className="space-y-4">
              {environmentalData.map((item, index) => (
                <div key={index} className="bg-white/5 rounded-lg p-4">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-gray-300 text-sm">{item.metric}</span>
                    <span className={`text-xs px-2 py-1 rounded-full ${getStatusColor(item.status)} bg-current bg-opacity-20`}>
                      {item.status}
                    </span>
                  </div>
                  <div className="flex justify-between items-end">
                    <span className="text-white font-medium text-lg">{item.value}</span>
                    <span className="text-green-400 text-sm">{item.trend}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* AI Insights */}
        <div className="mt-8 bg-white/10 backdrop-blur-sm rounded-xl p-6 border border-white/20">
          <h2 className="text-xl font-semibold text-white mb-6 flex items-center">
            <Cpu className="h-5 w-5 mr-2" />
            Amazon Bedrock AI Insights
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {insights.map((insight, index) => (
              <div key={index} className="bg-white/5 rounded-lg p-4">
                <div className="flex items-start justify-between mb-3">
                  <span className="text-2xl">{getInsightIcon(insight.type)}</span>
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                    insight.impact === 'High' ? 'bg-red-500/20 text-red-400' :
                    insight.impact === 'Medium' ? 'bg-yellow-500/20 text-yellow-400' :
                    'bg-blue-500/20 text-blue-400'
                  }`}>
                    {insight.impact} Impact
                  </span>
                </div>
                <h3 className="text-white font-medium mb-2">{insight.title}</h3>
                <p className="text-gray-300 text-sm">{insight.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* AI Recommendations */}
        <div className="mt-8 bg-gradient-to-r from-primary-500/20 to-secondary-500/20 backdrop-blur-sm rounded-xl p-6 border border-white/20">
          <h2 className="text-xl font-semibold text-white mb-4 flex items-center">
            <Cpu className="h-5 w-5 mr-2" />
            AI-Powered Recommendations
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h3 className="text-white font-medium mb-3">Priority Actions (AI Generated)</h3>
              <ul className="space-y-2">
                <li className="flex items-center text-gray-300 text-sm">
                  <div className="w-2 h-2 bg-red-400 rounded-full mr-3"></div>
                  Apply AI-recommended pest treatment to Field B immediately
                </li>
                <li className="flex items-center text-gray-300 text-sm">
                  <div className="w-2 h-2 bg-yellow-400 rounded-full mr-3"></div>
                  Adjust irrigation based on AI soil moisture predictions
                </li>
                <li className="flex items-center text-gray-300 text-sm">
                  <div className="w-2 h-2 bg-green-400 rounded-full mr-3"></div>
                  Begin harvest preparation based on AI maturity analysis
                </li>
              </ul>
            </div>
            <div>
              <h3 className="text-white font-medium mb-3">Optimization Opportunities</h3>
              <ul className="space-y-2">
                <li className="flex items-center text-gray-300 text-sm">
                  <div className="w-2 h-2 bg-blue-400 rounded-full mr-3"></div>
                  Implement AI-optimized drip irrigation schedule
                </li>
                <li className="flex items-center text-gray-300 text-sm">
                  <div className="w-2 h-2 bg-purple-400 rounded-full mr-3"></div>
                  Use AI companion planting recommendations
                </li>
                <li className="flex items-center text-gray-300 text-sm">
                  <div className="w-2 h-2 bg-indigo-400 rounded-full mr-3"></div>
                  Schedule AI-predicted optimal soil testing times
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;